[build]
  # Build command (not needed for static site)
  command = "echo 'Static site - no build process required'"
  
  # Publish directory
  publish = "."

[build.environment]
  # Node.js version (if needed)
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  # Redirect /admin to admin.html
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  # SPA fallback (optional)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!US"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=300"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Cache optimization
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
